name: ntfy_action
description: Send GitHub Action workflow notifications to ntfy.
branding:
  icon: "upload"
  color: "blue"
inputs:
  url:
    description: Server URL
    required: true
  topic:
    description: ntfy topic
    required: true
  tags:
    description: Tags for the message seperated by commas
    required: false
  title:
    description: ntfy message title.
    required: false
  headers:
    description: Authentication headers or others if needed.
    required: false
  details:
    description: Additional text after the notification message.
    required: false
  priority:
    description: Message priority.
    required: false
  actions:
    description: ntfy action buttons. Maximum 3 buttons.
    required: false
  image:
    description: Attach an image of the workflow.
    required: false
  icon:
    description: An icon that will appear next to the text of the notification
    required: false
outputs:
  response:
    description: "The response of POST request"
runs:
  using: "node20"
  main: "dist/index.js"
